-- ============================================================================
-- ORACLESHOP MANAGER — DATABASE SCHEMA (ORACLE XE COMPATIBLE)
-- ============================================================================

-- 1. DROP EXISTING TRIGGERS & TABLES (Ensuring a clean slate)
DECLARE
  PROCEDURE drop_table_if_exists(p_table_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_table_name || ' CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
        RAISE;
      END IF;
  END;
BEGIN
  drop_table_if_exists('PAYMENT');
  drop_table_if_exists('ORDER_ITEM');
  drop_table_if_exists('ORDERS');
  drop_table_if_exists('PRODUCT');
  drop_table_if_exists('CUSTOMER');
  drop_table_if_exists('USERS');
  drop_table_if_exists('AUDIT_LOG');
END;
/

-- 2. CREATE TABLES

-- USERS Table: User authentication credentials
CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password VARCHAR2(256) NOT NULL,
  role VARCHAR2(20) NOT NULL CHECK (role IN ('ADMIN', 'STAFF'))
);

-- CUSTOMER Table: Customer details
CREATE TABLE customer (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) UNIQUE NOT NULL,
  phone VARCHAR2(20) NOT NULL
);

-- PRODUCT Table: Product items and inventory
CREATE TABLE product (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name VARCHAR2(100) UNIQUE NOT NULL,
  price NUMBER(10, 2) NOT NULL CHECK (price >= 0),
  stock NUMBER NOT NULL CHECK (stock >= 0) -- Prevents negative stock via Check Constraint
);

-- ORDERS Table: Base transactions
CREATE TABLE orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'CANCELLED')),
  total_amount NUMBER(10, 2) DEFAULT 0.00 NOT NULL CHECK (total_amount >= 0)
);

-- ORDER_ITEM Table: Specific order rows (Many-to-Many connection between Orders and Products)
CREATE TABLE order_item (
  order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  product_id NUMBER NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  quantity NUMBER NOT NULL CHECK (quantity > 0)
);

-- PAYMENT Table: Payment transaction (1-to-1 relationship with Orders)
CREATE TABLE payment (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER NOT NULL UNIQUE REFERENCES orders(order_id) ON DELETE CASCADE,
  payment_method VARCHAR2(50) NOT NULL CHECK (payment_method IN ('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL')),
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- AUDIT_LOG Table: Store action history logs for verification
CREATE TABLE audit_log (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_type VARCHAR2(50) NOT NULL,
  description VARCHAR2(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
/

-- 3. CREATE TRIGGERS

-- Trigger A: TRG_UPDATE_STOCK
-- Automatically deducts inventory stock whenever a new order item is inserted.
-- If stock drops below zero, it violates the Check Constraint 'stock >= 0' on the product table,
-- causing a rollback of the entire insert transaction to enforce data validation.
CREATE OR REPLACE TRIGGER trg_update_stock
AFTER INSERT ON order_item
FOR EACH ROW
BEGIN
  -- Deduct stock from the product
  UPDATE product
  SET stock = stock - :NEW.quantity
  WHERE product_id = :NEW.product_id;
  
  -- Insert a log record of the inventory reduction
  INSERT INTO audit_log (action_type, description)
  VALUES (
    'STOCK_REDUCED',
    'Product ID: ' || :NEW.product_id || ' stock reduced by ' || :NEW.quantity || ' units for Order ID: ' || :NEW.order_id
  );
END;
/

-- Trigger B: TRG_CALCULATE_ORDER_TOTAL
-- Automatically calculates and updates the total_amount in the orders table based on quantity * product price.
CREATE OR REPLACE TRIGGER trg_calculate_order_total
AFTER INSERT ON order_item
FOR EACH ROW
DECLARE
  v_item_price NUMBER(10,2);
BEGIN
  -- Fetch the product price
  SELECT price INTO v_item_price
  FROM product
  WHERE product_id = :NEW.product_id;
  
  -- Add the item total amount to the parent order total
  UPDATE orders
  SET total_amount = total_amount + (v_item_price * :NEW.quantity)
  WHERE order_id = :NEW.order_id;
END;
/

-- Trigger C: TRG_PAYMENT_AUTO_STATUS
-- Automatically transitions an order's status to 'PAID' when a payment record is inserted.
CREATE OR REPLACE TRIGGER trg_payment_auto_status
AFTER INSERT ON payment
FOR EACH ROW
BEGIN
  UPDATE orders
  SET status = 'PAID'
  WHERE order_id = :NEW.order_id;
  
  INSERT INTO audit_log (action_type, description)
  VALUES (
    'ORDER_PAID',
    'Order ID: ' || :NEW.order_id || ' status changed to PAID via payment method: ' || :NEW.payment_method
  );
END;
/


-- 4. SEED DATA

-- Seeding Users (Minimum 3 system users)
-- admin -> 'admin123'
-- manager -> 'manager123'
-- staff1 -> 'staff123'
INSERT INTO users (username, password, role) VALUES ('admin', 'admin123', 'ADMIN');
INSERT INTO users (username, password, role) VALUES ('manager', 'manager123', 'ADMIN');
INSERT INTO users (username, password, role) VALUES ('staff1', 'staff123', 'STAFF');

-- Seeding Customers
INSERT INTO customer (name, email, phone) VALUES ('John Doe', 'john.doe@gmail.com', '+1234567890');
INSERT INTO customer (name, email, phone) VALUES ('Jane Smith', 'jane.smith@yahoo.com', '+1987654321');
INSERT INTO customer (name, email, phone) VALUES ('Bob Johnson', 'bob.j@outlook.com', '+1122334455');

-- Seeding Products
INSERT INTO product (product_name, price, stock) VALUES ('iPhone 15 Pro', 999.00, 10);
INSERT INTO product (product_name, price, stock) VALUES ('Samsung Galaxy S24 Ultra', 1199.50, 15);
INSERT INTO product (product_name, price, stock) VALUES ('Sony WH-1000XM5 Headphones', 349.99, 25);
INSERT INTO product (product_name, price, stock) VALUES ('MacBook Air M3', 1099.00, 8);
INSERT INTO product (product_name, price, stock) VALUES ('Dell XPS 13', 899.99, 12);
INSERT INTO product (product_name, price, stock) VALUES ('iPad Air', 599.00, 20);

COMMIT;
/
